# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='', max_length=1000)),
                ('hair_colour', models.CharField(choices=[('BLACK', 'Black'), ('BROWN', 'Brown'), ('BLONDE', 'Blonde'), ('RED', 'Red'), ('GREY', 'Grey'), ('BALD', 'Bald'), ('OTHER', 'Other')], default='BLACK', max_length=7)),
                ('body_type', models.CharField(choices=[('THIN', 'Thin'), ('NORMAL', 'Normal'), ('MUSCULAR', 'Muscular'), ('FIT', 'Fit'), ('A LITTLE EXTRA', 'A Little Extra'), ('CURVY', 'Curvy')], default='NORMAL', max_length=14)),
                ('looking_for', models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women'), ('BOTH', 'Both')], default='BOTH', max_length=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('signed_up_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
