# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190429_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=profiles.models.image_filename),
        ),
    ]
