# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190430_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
