# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190501_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citylat',
            field=models.DecimalField(decimal_places=6, default='-2.0180319', max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='citylong',
            field=models.DecimalField(decimal_places=6, default='52.5525525', max_digits=9),
        ),
    ]
