# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20190501_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
