# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profileimage_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.CharField(choices=[('TO BE APPROVED', 'To be approved'), ('APPROVED', 'Approved'), ('NOT APPROVED', 'Not approved')], default='TO BE APPROVED', max_length=14),
        ),
    ]
