# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20190502_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('HIGH SCHOOL', 'High School'), ('COLLEGE', 'College'), ('BACHELORS DEGREE', 'Bachelors Degree'), ('MASTERS', 'Masters'), ('PHD / POST DOCTORAL', 'PhD / Post Doctoral')], default='HIGH SCHOOL', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(choices=[('WHITE', 'White'), ('ASIAN: INDIAN', 'Asian: Indian'), ('ASIAN: PAKISTANI', 'Asian: Pakistani'), ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'), ('ASIAN: CHINESE', 'Asian: Chinese'), ('BLACK', 'Black'), ('MIXED', 'Mixed'), ('OTHER ETHNICITY', 'Other Ethnicity')], default='WHITE', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hair_length',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHOULDER LENGTH', 'Shoulder Length'), ('AVERAGE', 'Average'), ('SHORT', 'Short'), ('SHAVED', 'Shaved')], default='LONG', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('NEVER MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated')], default='NEVER MARRIED', max_length=100),
        ),
    ]
