# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-13 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Male'), ('WOMEN', 'Female')], default='MALE', max_length=6),
        ),
    ]
