# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20190613_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('MALE', 'Men'), ('FEMALE', 'Women'), ('BOTH', 'Both')], default='BOTH', max_length=5),
        ),
    ]
