# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20190616_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
