# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20190626_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hair_colour',
            field=models.CharField(choices=[('BLACK', 'Black'), ('BLONDE', 'Blonde'), ('BROWN', 'Brown'), ('RED', 'Red'), ('GREY', 'Grey'), ('BALD', 'Bald'), ('BLUE', 'Blue'), ('PINK', 'Pink'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple'), ('OTHER', 'Other')], default='BLACK', max_length=10),
        ),
    ]
