# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20190629_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(choices=[('152.4', "5' 0"), ('154.94', "5' 1"), ('157.48', "5' 2"), ('160.02', "5' 3"), ('162.56', "5' 4"), ('165.1', "5' 5"), ('167.64', "5' 6"), ('170.18', "5' 7"), ('172.72', "5' 8"), ('175.26', "5' 9"), ('177.8', "5' 10"), ('180.34', "5' 11"), ('182.88', "6' 0"), ('185.42', "6' 1"), ('187.96', "6' 2"), ('190.5', "6' 3"), ('193.04', "6' 4"), ('195.58', "6' 5"), ('198.12', "6' 6"), ('200.66', "6' 7"), ('203.2', "6' 8"), ('205.74', "6' 9"), ('208.28', "6' 10"), ('210.82', "6' 11")], decimal_places=2, default=100, max_digits=10),
        ),
    ]
