# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-11 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20190711_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, default=180.34, max_digits=10),
        ),
    ]
