from django.shortcuts import render
from profiles.models import Profile, ProfileImage
from django.db.models import Q, F
from django.db.models import Count
from django.contrib.auth.decorators import login_required
import datetime as DT
from django.contrib.auth.models import User
from chat.models import Conversations
import datetime
import stripe
from checkout.models import Subscription

# Home page after user logs in
@login_required
def index(request):

    
    # Query profiles in distance order for 'Closest to you' section
    if request.user.profile.looking_for == "BOTH":
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user_id=request.user.id).all()[:4]
    else:
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user_id=request.user.id).all()[:4]
    
    # Profiles for quick match finder, exclude users winked or rejected previously
    if request.user.profile.looking_for == "BOTH":
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).exclude(user__rejected_receiver__sender_id=request.user.id).all()[:10]
    else:
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).exclude(user__rejected_receiver__sender_id=request.user.id).all()[:10]
    
    if card_profiles.count() == 0:
        card_profiles_exists = False
    else: 
        card_profiles_exists = True
    
    
    today = DT.date.today()
    one_week_ago = today - DT.timedelta(days=7)
    # Profiles for active most recently, excluding those who signed up in the last 7 days
    if request.user.profile.looking_for == "BOTH":
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4]
    else:
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4] 
    
    # Profiles ordered by signed up date for 'Newcomers' section
    if request.user.profile.looking_for == "BOTH":
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4]
    else:
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.citylat), float(request.user.profile.citylong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4] 

    context = {
        'page_ref': 'home',
        'card_profiles_exists' : card_profiles_exists,
        'closest_profiles':closest_profiles,
        'active_profiles':active_profiles,
        'newest_profiles': newest_profiles,
        'card_profiles': card_profiles
    }
    
    return render(request, 'home.html', context)
    
# Home page before logged in/registered
def preregister(request):
    profiles = {
        '1':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1976-09-02","user_id":1,"hair_colour":"BLACK","body_type":"CURVY","looking_for":"BOTH","hair_length":"LONG","ethnicity":"ASIAN: PAKISTANI","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"MALE"},
        '2':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1985-02-28","user_id":2,"hair_colour":"RED","body_type":"THIN","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '3':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1982-01-07","user_id":3,"hair_colour":"OTHER","body_type":"FIT","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"WHITE","relationship_status":"NEVER MARRIED","education":"COLLEGE","gender":"MALE"},
        '4':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1999-06-14","user_id":4,"hair_colour":"BLACK","body_type":"A LITTLE EXTRA","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"WHITE","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '5':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1978-02-19","user_id":5,"hair_colour":"BLACK","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"WHITE","relationship_status":"SEPARATED","education":"MASTERS","gender":"MALE"},
        '6':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1991-12-20","user_id":6,"hair_colour":"BLONDE","body_type":"MUSCULAR","looking_for":"FEMALE","hair_length":"SHAVED","ethnicity":"BLACK","relationship_status":"DIVORCED","education":"COLLEGE","gender":"FEMALE"},
        '7':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1988-06-05","user_id":7,"hair_colour":"OTHER","body_type":"FIT","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"DIVORCED","education":"MASTERS","gender":"MALE"},
        '8':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-11-19","user_id":8,"hair_colour":"RED","body_type":"FIT","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '9':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1986-05-04","user_id":9,"hair_colour":"BLUE","body_type":"FIT","looking_for":"MALE","hair_length":"SHAVED","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"SEPARATED","education":"HIGH SCHOOL","gender":"MALE"},
        '10':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-01-25","user_id":10,"hair_colour":"RED","body_type":"MUSCULAR","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"MIXED","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '11':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1977-04-29","user_id":11,"hair_colour":"BROWN","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"ASIAN: CHINESE","relationship_status":"NEVER MARRIED","education":"HIGH SCHOOL","gender":"MALE"},
        '12':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1990-09-03","user_id":12,"hair_colour":"PINK","body_type":"A LITTLE EXTRA","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"SEPARATED","education":"MASTERS","gender":"FEMALE"},
        '13':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1979-02-17","user_id":13,"hair_colour":"PINK","body_type":"THIN","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"ASIAN: CHINESE","relationship_status":"DIVORCED","education":"BACHELORS DEGREE","gender":"MALE"},
        '14':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-11-06","user_id":14,"hair_colour":"BALD","body_type":"FIT","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"BLACK","relationship_status":"WIDOWED","education":"COLLEGE","gender":"FEMALE"},
        '15':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-07-25","user_id":15,"hair_colour":"BLACK","body_type":"THIN","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"ASIAN: INDIAN","relationship_status":"DIVORCED","education":"COLLEGE","gender":"MALE"},
        '16':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1997-07-06","user_id":16,"hair_colour":"BLACK","body_type":"FIT","looking_for":"MALE","hair_length":"LONG","ethnicity":"ASIAN: PAKISTANI","relationship_status":"DIVORCED","education":"COLLEGE","gender":"FEMALE"},
        '17':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1985-01-28","user_id":17,"hair_colour":"PINK","body_type":"CURVY","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: INDIAN","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"MALE"},
        '18':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1986-05-15","user_id":18,"hair_colour":"BLACK","body_type":"AVERAGE","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"WHITE","relationship_status":"SEPARATED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '19':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1978-07-28","user_id":19,"hair_colour":"BLACK","body_type":"FIT","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"BLACK","relationship_status":"DIVORCED","education":"COLLEGE","gender":"MALE"},
        '20':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1974-04-15","user_id":20,"hair_colour":"OTHER","body_type":"THIN","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"NEVER MARRIED","education":"COLLEGE","gender":"FEMALE"},
        '21':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1982-11-06","user_id":21,"hair_colour":"OTHER","body_type":"MUSCULAR","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"ASIAN: INDIAN","relationship_status":"SEPARATED","education":"BACHELORS DEGREE","gender":"MALE"},
        '22':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1997-04-17","user_id":22,"hair_colour":"RED","body_type":"A LITTLE EXTRA","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"SEPARATED","education":"MASTERS","gender":"FEMALE"},
        '23':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-05-30","user_id":23,"hair_colour":"BLONDE","body_type":"THIN","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: INDIAN","relationship_status":"SEPARATED","education":"COLLEGE","gender":"MALE"},
        '24':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1995-01-03","user_id":24,"hair_colour":"BROWN","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"LONG","ethnicity":"ASIAN: PAKISTANI","relationship_status":"DIVORCED","education":"BACHELORS DEGREE","gender":"FEMALE"},
        '25':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1989-09-09","user_id":25,"hair_colour":"GREY","body_type":"THIN","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"BLACK","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '26':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1998-12-28","user_id":26,"hair_colour":"PURPLE","body_type":"MUSCULAR","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"ASIAN: INDIAN","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"FEMALE"},
        '27':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1984-07-18","user_id":27,"hair_colour":"BLUE","body_type":"THIN","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"MIXED","relationship_status":"WIDOWED","education":"BACHELORS DEGREE","gender":"MALE"},
        '28':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1989-08-26","user_id":28,"hair_colour":"BLONDE","body_type":"CURVY","looking_for":"MALE","hair_length":"LONG","ethnicity":"BLACK","relationship_status":"NEVER MARRIED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '29':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-07-06","user_id":29,"hair_colour":"BLUE","body_type":"FIT","looking_for":"MALE","hair_length":"SHAVED","ethnicity":"BLACK","relationship_status":"SEPARATED","education":"COLLEGE","gender":"MALE"},
        '30':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1994-10-11","user_id":30,"hair_colour":"BLUE","body_type":"A LITTLE EXTRA","looking_for":"MALE","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '31':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-10-05","user_id":31,"hair_colour":"OTHER","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"OTHER ETHNICITY","relationship_status":"DIVORCED","education":"COLLEGE","gender":"MALE"},
        '32':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1980-05-22","user_id":32,"hair_colour":"PURPLE","body_type":"FIT","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"SEPARATED","education":"COLLEGE","gender":"FEMALE"},
        '33':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1994-04-26","user_id":33,"hair_colour":"PURPLE","body_type":"AVERAGE","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"MIXED","relationship_status":"NEVER MARRIED","education":"HIGH SCHOOL","gender":"MALE"},
        '34':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1994-10-09","user_id":34,"hair_colour":"RED","body_type":"THIN","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"SEPARATED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '35':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-10-13","user_id":35,"hair_colour":"BALD","body_type":"CURVY","looking_for":"FEMALE","hair_length":"SHORT","ethnicity":"MIXED","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"MALE"},
        '36':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-05-21","user_id":36,"hair_colour":"OTHER","body_type":"FIT","looking_for":"MALE","hair_length":"LONG","ethnicity":"MIXED","relationship_status":"WIDOWED","education":"COLLEGE","gender":"FEMALE"},
        '37':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1996-02-12","user_id":37,"hair_colour":"PINK","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"WHITE","relationship_status":"SEPARATED","education":"COLLEGE","gender":"MALE"},
        '38':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1994-12-10","user_id":38,"hair_colour":"RED","body_type":"FIT","looking_for":"MALE","hair_length":"LONG","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"WIDOWED","education":"COLLEGE","gender":"FEMALE"},
        '39':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-11-03","user_id":39,"hair_colour":"PURPLE","body_type":"THIN","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"BLACK","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"MALE"},
        '40':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1976-07-30","user_id":40,"hair_colour":"GREY","body_type":"THIN","looking_for":"FEMALE","hair_length":"SHORT","ethnicity":"OTHER ETHNICITY","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '41':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1997-11-14","user_id":41,"hair_colour":"RED","body_type":"FIT","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"WHITE","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '42':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1978-09-13","user_id":42,"hair_colour":"BLUE","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: INDIAN","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '43':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1974-08-13","user_id":43,"hair_colour":"BLUE","body_type":"THIN","looking_for":"BOTH","hair_length":"SHOULDER LENGTH","ethnicity":"MIXED","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '44':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1981-11-23","user_id":44,"hair_colour":"GREEN","body_type":"A LITTLE EXTRA","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"WIDOWED","education":"MASTERS","gender":"FEMALE"},
        '45':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-08-05","user_id":45,"hair_colour":"OTHER","body_type":"MUSCULAR","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: CHINESE","relationship_status":"DIVORCED","education":"MASTERS","gender":"MALE"},
        '46':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1972-09-25","user_id":46,"hair_colour":"GREY","body_type":"A LITTLE EXTRA","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '47':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-03-13","user_id":47,"hair_colour":"OTHER","body_type":"THIN","looking_for":"MALE","hair_length":"LONG","ethnicity":"ASIAN: CHINESE","relationship_status":"SEPARATED","education":"BACHELORS DEGREE","gender":"MALE"},
        '48':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1987-09-03","user_id":48,"hair_colour":"PINK","body_type":"A LITTLE EXTRA","looking_for":"MALE","hair_length":"SHORT","ethnicity":"ASIAN: PAKISTANI","relationship_status":"SEPARATED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '49':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-01-01","user_id":49,"hair_colour":"BLACK","body_type":"CURVY","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"MALE"},
        '50':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1970-11-05","user_id":50,"hair_colour":"BALD","body_type":"MUSCULAR","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"OTHER ETHNICITY","relationship_status":"DIVORCED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '51':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1989-09-28","user_id":51,"hair_colour":"RED","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"WHITE","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"MALE"},
        '52':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-08-04","user_id":52,"hair_colour":"RED","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: PAKISTANI","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '53':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1985-07-07","user_id":53,"hair_colour":"BLONDE","body_type":"CURVY","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"ASIAN: INDIAN","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"MALE"},
        '54':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1974-03-24","user_id":54,"hair_colour":"RED","body_type":"A LITTLE EXTRA","looking_for":"MALE","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"DIVORCED","education":"COLLEGE","gender":"FEMALE"},
        '55':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1975-06-25","user_id":55,"hair_colour":"PINK","body_type":"THIN","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"ASIAN: CHINESE","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"MALE"},
        '56':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1997-09-18","user_id":56,"hair_colour":"BALD","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"ASIAN: INDIAN","relationship_status":"NEVER MARRIED","education":"COLLEGE","gender":"FEMALE"},
        '57':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-11-27","user_id":57,"hair_colour":"BLUE","body_type":"THIN","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"MIXED","relationship_status":"DIVORCED","education":"COLLEGE","gender":"MALE"},
        '58':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1988-11-06","user_id":58,"hair_colour":"PINK","body_type":"FIT","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"MIXED","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '59':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1996-04-20","user_id":59,"hair_colour":"RED","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"WHITE","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"MALE"},
        '60':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1990-04-14","user_id":60,"hair_colour":"BLUE","body_type":"AVERAGE","looking_for":"FEMALE","hair_length":"SHORT","ethnicity":"ASIAN: PAKISTANI","relationship_status":"SEPARATED","education":"COLLEGE","gender":"FEMALE"},
        '61':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-12-12","user_id":61,"hair_colour":"OTHER","body_type":"MUSCULAR","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"BLACK","relationship_status":"SEPARATED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '62':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1998-08-14","user_id":62,"hair_colour":"RED","body_type":"THIN","looking_for":"BOTH","hair_length":"LONG","ethnicity":"ASIAN: PAKISTANI","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '63':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1994-10-24","user_id":63,"hair_colour":"PINK","body_type":"THIN","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"MIXED","relationship_status":"DIVORCED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '64':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1982-12-27","user_id":64,"hair_colour":"GREEN","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"FEMALE"},
        '65':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1987-03-27","user_id":65,"hair_colour":"GREEN","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"MIXED","relationship_status":"SEPARATED","education":"HIGH SCHOOL","gender":"MALE"},
        '66':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1996-01-21","user_id":66,"hair_colour":"BLACK","body_type":"AVERAGE","looking_for":"FEMALE","hair_length":"SHAVED","ethnicity":"WHITE","relationship_status":"SEPARATED","education":"MASTERS","gender":"FEMALE"},
        '67':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1974-07-29","user_id":67,"hair_colour":"GREEN","body_type":"CURVY","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"WHITE","relationship_status":"SEPARATED","education":"COLLEGE","gender":"MALE"},
        '68':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-12-14","user_id":68,"hair_colour":"GREY","body_type":"THIN","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"OTHER ETHNICITY","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '69':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1992-10-13","user_id":69,"hair_colour":"PINK","body_type":"AVERAGE","looking_for":"MALE","hair_length":"SHORT","ethnicity":"ASIAN: CHINESE","relationship_status":"WIDOWED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '70':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1999-03-16","user_id":70,"hair_colour":"BALD","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"COLLEGE","gender":"FEMALE"},
        '71':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1981-06-10","user_id":71,"hair_colour":"BLONDE","body_type":"CURVY","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"BACHELORS DEGREE","gender":"MALE"},
        '72':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1990-03-01","user_id":72,"hair_colour":"RED","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"ASIAN: PAKISTANI","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '73':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1979-05-30","user_id":73,"hair_colour":"BLACK","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"DIVORCED","education":"COLLEGE","gender":"MALE"},
        '74':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"2000-02-29","user_id":74,"hair_colour":"BLACK","body_type":"FIT","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"ASIAN: CHINESE","relationship_status":"SEPARATED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '75':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-03-02","user_id":75,"hair_colour":"GREEN","body_type":"AVERAGE","looking_for":"MALE","hair_length":"LONG","ethnicity":"ASIAN: CHINESE","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"MALE"},
        '76':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1996-03-03","user_id":76,"hair_colour":"BROWN","body_type":"THIN","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"BLACK","relationship_status":"SEPARATED","education":"MASTERS","gender":"FEMALE"},
        '77':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1975-03-31","user_id":77,"hair_colour":"RED","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"LONG","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"MASTERS","gender":"MALE"},
        '78':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1972-09-06","user_id":78,"hair_colour":"PINK","body_type":"MUSCULAR","looking_for":"MALE","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"FEMALE"},
        '79':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1990-11-26","user_id":79,"hair_colour":"BALD","body_type":"CURVY","looking_for":"FEMALE","hair_length":"LONG","ethnicity":"ASIAN: PAKISTANI","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"MALE"},
        '80':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1986-10-04","user_id":80,"hair_colour":"BROWN","body_type":"AVERAGE","looking_for":"MALE","hair_length":"SHORT","ethnicity":"MIXED","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"FEMALE"},
        '81':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1992-11-24","user_id":81,"hair_colour":"PURPLE","body_type":"CURVY","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"MIXED","relationship_status":"NEVER MARRIED","education":"COLLEGE","gender":"MALE"},
        '82':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-08-04","user_id":82,"hair_colour":"OTHER","body_type":"FIT","looking_for":"MALE","hair_length":"SHORT","ethnicity":"ASIAN: CHINESE","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"FEMALE"},
        '83':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1975-03-17","user_id":83,"hair_colour":"BLACK","body_type":"AVERAGE","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"MIXED","relationship_status":"NEVER MARRIED","education":"BACHELORS DEGREE","gender":"MALE"},
        '84':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1993-10-09","user_id":84,"hair_colour":"GREY","body_type":"THIN","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"WHITE","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '85':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1990-05-13","user_id":85,"hair_colour":"OTHER","body_type":"AVERAGE","looking_for":"MALE","hair_length":"SHORT","ethnicity":"ASIAN: INDIAN","relationship_status":"DIVORCED","education":"MASTERS","gender":"MALE"},
        '86':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-06-05","user_id":86,"hair_colour":"BROWN","body_type":"AVERAGE","looking_for":"MALE","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '87':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-01-30","user_id":87,"hair_colour":"BLUE","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"BACHELORS DEGREE","gender":"MALE"},
        '88':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-01-05","user_id":88,"hair_colour":"GREEN","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"LONG","ethnicity":"MIXED","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"FEMALE"},
        '89':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1974-02-22","user_id":89,"hair_colour":"GREEN","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"AVERAGE","ethnicity":"ASIAN: PAKISTANI","relationship_status":"WIDOWED","education":"HIGH SCHOOL","gender":"MALE"},
        '90':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1983-08-05","user_id":90,"hair_colour":"OTHER","body_type":"MUSCULAR","looking_for":"FEMALE","hair_length":"SHAVED","ethnicity":"OTHER ETHNICITY","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"FEMALE"},
        '91':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1973-06-22","user_id":91,"hair_colour":"GREEN","body_type":"AVERAGE","looking_for":"FEMALE","hair_length":"SHAVED","ethnicity":"BLACK","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '92':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1978-03-03","user_id":92,"hair_colour":"BLACK","body_type":"AVERAGE","looking_for":"FEMALE","hair_length":"SHORT","ethnicity":"BLACK","relationship_status":"WIDOWED","education":"COLLEGE","gender":"FEMALE"},
        '93':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1972-02-06","user_id":93,"hair_colour":"BALD","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"SHORT","ethnicity":"OTHER ETHNICITY","relationship_status":"WIDOWED","education":"COLLEGE","gender":"MALE"},
        '94':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1996-03-10","user_id":94,"hair_colour":"BROWN","body_type":"CURVY","looking_for":"MALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"DIVORCED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '95':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-05-01","user_id":95,"hair_colour":"GREEN","body_type":"AVERAGE","looking_for":"MALE","hair_length":"LONG","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"NEVER MARRIED","education":"MASTERS","gender":"MALE"},
        '96':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1985-07-09","user_id":96,"hair_colour":"GREY","body_type":"THIN","looking_for":"FEMALE","hair_length":"AVERAGE","ethnicity":"ASIAN: BANGLADESHI","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '97':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1976-07-18","user_id":97,"hair_colour":"BLACK","body_type":"A LITTLE EXTRA","looking_for":"BOTH","hair_length":"SHAVED","ethnicity":"ASIAN: CHINESE","relationship_status":"DIVORCED","education":"HIGH SCHOOL","gender":"MALE"},
        '98':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1971-12-07","user_id":98,"hair_colour":"GREEN","body_type":"MUSCULAR","looking_for":"BOTH","hair_length":"SHOULDER LENGTH","ethnicity":"WHITE","relationship_status":"NEVER MARRIED","education":"PHD / POST DOCTORAL","gender":"FEMALE"},
        '99':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1988-06-09","user_id":99,"hair_colour":"GREY","body_type":"CURVY","looking_for":"FEMALE","hair_length":"SHOULDER LENGTH","ethnicity":"ASIAN: INDIAN","relationship_status":"SEPARATED","education":"PHD / POST DOCTORAL","gender":"MALE"},
        '100':{"bio":"I haven’t dated much in recent years because I’ve been so focused on my career. Now I’m ready to meet the person who will pull my head out of the books and bring me a bit of happiness.","birth_date":"1995-04-22","user_id":100,"hair_colour":"BALD","body_type":"CURVY","looking_for":"MALE","hair_length":"SHORT","ethnicity":"ASIAN: CHINESE","relationship_status":"SEPARATED","education":"BACHELORS DEGREE","gender":"FEMALE"}
    }
    
    for k, v in profiles.items():
        profile = Profile.objects.get(pk=k)
        profile.bio = v['bio']
        profile.birth_date=v['birth_date']
        profile.hair_colour=v['hair_colour']
        profile.body_type=v['body_type']
        profile.looking_for=v['looking_for']
        profile.hair_length=v['hair_length']
        profile.ethnicity=v['ethnicity']
        profile.relationship_status=v['relationship_status']
        profile.education=v['education']
        profile.gender=v['gender']

        profile.save()
        
    return render(request, 'index.html')