from django.shortcuts import render
from profiles.models import Profile
from django.db.models import Q, F
from django.db.models import Count
from django.contrib.auth.decorators import login_required
import datetime as DT
from django.contrib.auth.models import User


# Create your views here.
@login_required
def index(request):

    # Change limit
    # 'or' needed in gender check https://stackoverflow.com/questions/739776/how-do-i-do-an-or-filter-in-a-django-query
    # Exclude current user
    # Nearby Profiles
    if request.user.profile.looking_for == "BOTH":
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user_id=request.user.id).all()[:4]
    else:
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user_id=request.user.id).all()[:4]
    
    # Profiles for quick match finder
    if request.user.profile.looking_for == "BOTH":
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).all()
    else:
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).all()
    
    today = DT.date.today()
    one_week_ago = today - DT.timedelta(days=7)
    # Filter date_joined
    # Profiles for active most recently  
    if request.user.profile.looking_for == "BOTH":
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4]
    else:
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4] 
    
    # Profiles for newest
    if request.user.profile.looking_for == "BOTH":
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4]
    else:
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4] 

    context = {
        'closest_profiles':closest_profiles,
        'active_profiles':active_profiles,
        'newest_profiles': newest_profiles,
        'card_profiles': card_profiles
    }
    
    return render(request, 'index.html', context)
    
def preregister(request):

    profile = {
        'user1':{"bio":"erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet","birth_date":"1980-02-05","user_id":102,"body_type":"AVERAGE","hair_colour":"GREEN","looking_for":"BOTH","children":True,"education":"COLLEGE","ethnicity":"ASIAN: PAKISTANI","hair_length":"LONG","relationship_status":"WIDOWED",'gender':'MALE',"height":155.6},
        'user2':{"bio":"ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu","birth_date":"1986-04-10","user_id":2,"body_type":"THIN","hair_colour":"GREY","looking_for":'MALE',"children":True,"education":"HIGH SCHOOL","ethnicity":"WHITE","hair_length":"LONG","relationship_status":"SEPARATED",'gender':'MALE',"height":193.4},
        'user3':{"bio":"id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices","birth_date":"1983-03-24","user_id":4,"body_type":"A LITTLE EXTRA","hair_colour":"PINK","looking_for":"BOTH","children":False,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"SEPARATED",'gender':'MALE',"height":167.7},
        'user4':{"bio":"ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus","birth_date":"1982-03-25","user_id":11,"body_type":"THIN","hair_colour":"BLACK","looking_for":"BOTH","children":False,"education":"COLLEGE","ethnicity":"WHITE","hair_length":"SHAVED","relationship_status":"WIDOWED",'gender':'MALE',"height":175.5},
        'user5':{"bio":"orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras","birth_date":"1990-06-25","user_id":13,"body_type":"CURVY","hair_colour":"BALD","looking_for":'MALE',"children":False,"education":"MASTERS","ethnicity":"ASIAN: BANGLADESHI","hair_length":"SHOULDER LENGTH","relationship_status":"WIDOWED",'gender':'MALE',"height":190.0},
        'user6':{"bio":"sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci","birth_date":"1984-01-30","user_id":14,"body_type":"AVERAGE","hair_colour":"OTHER","looking_for":"FEMALE","children":True,"education":"PHD / POST DOCTORAL","ethnicity":"BLACK","hair_length":"LONG","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":175.9},
        'user7':{"bio":"a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis","birth_date":"1985-08-14","user_id":17,"body_type":"FIT","hair_colour":"BROWN","looking_for":'MALE',"children":False,"education":"PHD / POST DOCTORAL","ethnicity":"BLACK","hair_length":"AVERAGE","relationship_status":"DIVORCED",'gender':'MALE',"height":179.6},
        'user8':{"bio":"porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in","birth_date":"1987-04-03","user_id":18,"body_type":"FIT","hair_colour":"BLACK","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: BANGLADESHI","hair_length":"AVERAGE","relationship_status":"SEPARATED",'gender':'MALE',"height":174.4},
        'user9':{"bio":"sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla","birth_date":"1979-11-23","user_id":19,"body_type":"MUSCULAR","hair_colour":"BALD","looking_for":'MALE',"children":False,"education":"MASTERS","ethnicity":"WHITE","hair_length":"LONG","relationship_status":"DIVORCED",'gender':'MALE',"height":173.8},
        'user10':{"bio":"amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis","birth_date":"1980-02-23","user_id":22,"body_type":"AVERAGE","hair_colour":"OTHER","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: BANGLADESHI","hair_length":"SHOULDER LENGTH","relationship_status":"WIDOWED",'gender':'MALE',"height":184.4},
        'user11':{"bio":"dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id","birth_date":"1984-06-06","user_id":23,"body_type":"THIN","hair_colour":"BLUE","looking_for":'MALE',"children":False,"education":"MASTERS","ethnicity":"OTHER ETHNICITY","hair_length":"LONG","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":194.4},
        'user12':{"bio":"non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus","birth_date":"1981-01-24","user_id":25,"body_type":"MUSCULAR","hair_colour":"BALD","looking_for":"BOTH","children":False,"education":"MASTERS","ethnicity":"MIXED","hair_length":"SHAVED","relationship_status":"WIDOWED",'gender':'MALE',"height":166.2},
        'user13':{"bio":"mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh","birth_date":"1986-06-13","user_id":26,"body_type":"MUSCULAR","hair_colour":"RED","looking_for":'MALE',"children":False,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: PAKISTANI","hair_length":"AVERAGE","relationship_status":"DIVORCED",'gender':'MALE',"height":170.9},
        'user14':{"bio":"nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi","birth_date":"1982-09-28","user_id":30,"body_type":"CURVY","hair_colour":"BALD","looking_for":'MALE',"children":True,"education":"BACHELORS DEGREE","ethnicity":"WHITE","hair_length":"LONG","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":156.2},
        'user15':{"bio":"posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis","birth_date":"1982-07-27","user_id":31,"body_type":"AVERAGE","hair_colour":"GREEN","looking_for":"BOTH","children":False,"education":"MASTERS","ethnicity":"MIXED","hair_length":"AVERAGE","relationship_status":"SEPARATED",'gender':'MALE',"height":150.4},
        'user16':{"bio":"maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla","birth_date":"1972-08-15","user_id":34,"body_type":"CURVY","hair_colour":"PINK","looking_for":"FEMALE","children":False,"education":"BACHELORS DEGREE","ethnicity":"WHITE","hair_length":"SHAVED","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":186.3},
        'user17':{"bio":"rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo","birth_date":"1980-03-22","user_id":38,"body_type":"THIN","hair_colour":"GREY","looking_for":'MALE',"children":False,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: CHINESE","hair_length":"SHOULDER LENGTH","relationship_status":"SEPARATED",'gender':'MALE',"height":169.5},
        'user18':{"bio":"est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in","birth_date":"1972-03-06","user_id":39,"body_type":"CURVY","hair_colour":"GREEN","looking_for":'MALE',"children":False,"education":"BACHELORS DEGREE","ethnicity":"WHITE","hair_length":"SHAVED","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":197.5},
        'user19':{"bio":"potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus","birth_date":"1989-12-13","user_id":40,"body_type":"A LITTLE EXTRA","hair_colour":"BALD","looking_for":"FEMALE","children":True,"education":"HIGH SCHOOL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHORT","relationship_status":"SEPARATED",'gender':'MALE',"height":190.5},
        'user20':{"bio":"augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est","birth_date":"1980-02-08","user_id":43,"body_type":"AVERAGE","hair_colour":"GREEN","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"BLACK","hair_length":"AVERAGE","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":187.6},
        'user21':{"bio":"dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet","birth_date":"1988-03-02","user_id":44,"body_type":"CURVY","hair_colour":"OTHER","looking_for":'MALE',"children":True,"education":"COLLEGE","ethnicity":"WHITE","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":171.6},
        'user22':{"bio":"duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est","birth_date":"1975-07-08","user_id":46,"body_type":"CURVY","hair_colour":"PINK","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: INDIAN","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":195.1},
        'user23':{"bio":"ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim","birth_date":"1970-09-28","user_id":48,"body_type":"AVERAGE","hair_colour":"BLUE","looking_for":"BOTH","children":False,"education":"COLLEGE","ethnicity":"OTHER ETHNICITY","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':'MALE',"height":185.5},
        'user24':{"bio":"odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum","birth_date":"1983-09-30","user_id":49,"body_type":"THIN","hair_colour":"BLONDE","looking_for":"BOTH","children":True,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"WIDOWED",'gender':'MALE',"height":165.2},
        'user25':{"bio":"non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero","birth_date":"1986-12-12","user_id":56,"body_type":"AVERAGE","hair_colour":"BLACK","looking_for":"BOTH","children":False,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: BANGLADESHI","hair_length":"SHOULDER LENGTH","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":179.1},
        'user26':{"bio":"sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet","birth_date":"1971-05-26","user_id":57,"body_type":"AVERAGE","hair_colour":"RED","looking_for":"BOTH","children":False,"education":"HIGH SCHOOL","ethnicity":"BLACK","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":184.0},
        'user27':{"bio":"quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis","birth_date":"1976-04-10","user_id":60,"body_type":"CURVY","hair_colour":"RED","looking_for":"BOTH","children":True,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"SEPARATED",'gender':'MALE',"height":175.2},
        'user28':{"bio":"auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu","birth_date":"1986-05-21","user_id":63,"body_type":"CURVY","hair_colour":"BLONDE","looking_for":"BOTH","children":True,"education":"HIGH SCHOOL","ethnicity":"MIXED","hair_length":"AVERAGE","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":175.1},
        'user29':{"bio":"rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat","birth_date":"1974-12-21","user_id":66,"body_type":"MUSCULAR","hair_colour":"BROWN","looking_for":"FEMALE","children":True,"education":"COLLEGE","ethnicity":"OTHER ETHNICITY","hair_length":"LONG","relationship_status":"SEPARATED",'gender':'MALE',"height":199.5},
        'user30':{"bio":"tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed","birth_date":"1971-01-02","user_id":67,"body_type":"A LITTLE EXTRA","hair_colour":"BLACK","looking_for":"FEMALE","children":True,"education":"MASTERS","ethnicity":"ASIAN: CHINESE","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":178.5},
        'user31':{"bio":"sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum","birth_date":"1976-12-24","user_id":68,"body_type":"MUSCULAR","hair_colour":"OTHER","looking_for":"FEMALE","children":False,"education":"BACHELORS DEGREE","ethnicity":"BLACK","hair_length":"SHORT","relationship_status":"SEPARATED",'gender':'MALE',"height":182.9},
        'user32':{"bio":"sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut","birth_date":"1975-07-15","user_id":71,"body_type":"CURVY","hair_colour":"PURPLE","looking_for":"FEMALE","children":False,"education":"COLLEGE","ethnicity":"MIXED","hair_length":"SHOULDER LENGTH","relationship_status":"DIVORCED",'gender':'MALE',"height":151.8},
        'user33':{"bio":"ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas","birth_date":"1989-10-24","user_id":72,"body_type":"A LITTLE EXTRA","hair_colour":"BROWN","looking_for":'MALE',"children":True,"education":"COLLEGE","ethnicity":"OTHER ETHNICITY","hair_length":"AVERAGE","relationship_status":"WIDOWED",'gender':'MALE',"height":180.6},
        'user34':{"bio":"erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum","birth_date":"1975-05-07","user_id":73,"body_type":"CURVY","hair_colour":"BLONDE","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"DIVORCED",'gender':'MALE',"height":182.8},
        'user35':{"bio":"quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc","birth_date":"1979-04-12","user_id":74,"body_type":"A LITTLE EXTRA","hair_colour":"BLUE","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHORT","relationship_status":"WIDOWED",'gender':'MALE',"height":181.0},
        'user36':{"bio":"nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit","birth_date":"1989-07-27","user_id":75,"body_type":"MUSCULAR","hair_colour":"BALD","looking_for":"FEMALE","children":True,"education":"HIGH SCHOOL","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":186.0},
        'user37':{"bio":"nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et","birth_date":"1981-05-14","user_id":76,"body_type":"FIT","hair_colour":"BLUE","looking_for":'MALE',"children":False,"education":"PHD / POST DOCTORAL","ethnicity":"OTHER ETHNICITY","hair_length":"AVERAGE","relationship_status":"DIVORCED",'gender':'MALE',"height":167.6},
        'user38':{"bio":"purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla","birth_date":"1970-12-08","user_id":78,"body_type":"THIN","hair_colour":"BALD","looking_for":'MALE',"children":True,"education":"COLLEGE","ethnicity":"ASIAN: INDIAN","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":175.5},
        'user39':{"bio":"vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum","birth_date":"1985-05-21","user_id":79,"body_type":"CURVY","hair_colour":"GREEN","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"MIXED","hair_length":"LONG","relationship_status":"WIDOWED",'gender':'MALE',"height":173.2},
        'user40':{"bio":"congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi","birth_date":"1984-07-08","user_id":80,"body_type":"AVERAGE","hair_colour":"BROWN","looking_for":'MALE',"children":True,"education":"PHD / POST DOCTORAL","ethnicity":"WHITE","hair_length":"SHOULDER LENGTH","relationship_status":"NEVER MARRIED",'gender':'MALE',"height":199.4},
        'user41':{"bio":"et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla","birth_date":"1976-09-25","user_id":81,"body_type":"THIN","hair_colour":"BLACK","looking_for":"BOTH","children":True,"education":"PHD / POST DOCTORAL","ethnicity":"BLACK","hair_length":"LONG","relationship_status":"SEPARATED",'gender':'MALE',"height":174.4},
        'user42':{"bio":"habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla","birth_date":"1972-10-11","user_id":86,"body_type":"FIT","hair_colour":"BLONDE","looking_for":"FEMALE","children":True,"education":"HIGH SCHOOL","ethnicity":"MIXED","hair_length":"SHOULDER LENGTH","relationship_status":"DIVORCED",'gender':'MALE',"height":192.4},
        'user43':{"bio":"rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo","birth_date":"1985-01-29","user_id":87,"body_type":"THIN","hair_colour":"PURPLE","looking_for":"FEMALE","children":False,"education":"COLLEGE","ethnicity":"OTHER ETHNICITY","hair_length":"LONG","relationship_status":"SEPARATED",'gender':'MALE',"height":168.9},
        'user44':{"bio":"nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh","birth_date":"1975-03-14","user_id":89,"body_type":"AVERAGE","hair_colour":"BLUE","looking_for":"FEMALE","children":True,"education":"COLLEGE","ethnicity":"ASIAN: INDIAN","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':'MALE',"height":161.5},
        'user45':{"bio":"risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia","birth_date":"1989-07-22","user_id":95,"body_type":"A LITTLE EXTRA","hair_colour":"BLONDE","looking_for":"BOTH","children":False,"education":"BACHELORS DEGREE","ethnicity":"WHITE","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':'MALE',"height":152.8},
        'user46':{"bio":"ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar","birth_date":"1990-04-26","user_id":96,"body_type":"CURVY","hair_colour":"PURPLE","looking_for":'MALE',"children":True,"education":"HIGH SCHOOL","ethnicity":"ASIAN: CHINESE","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":184.2},
        'user47':{"bio":"vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis","birth_date":"1985-02-22","user_id":97,"body_type":"A LITTLE EXTRA","hair_colour":"PINK","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"OTHER ETHNICITY","hair_length":"LONG","relationship_status":"DIVORCED",'gender':'MALE',"height":159.0},
        'user48':{"bio":"elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a","birth_date":"1984-11-12","user_id":99,"body_type":"CURVY","hair_colour":"BALD","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"OTHER ETHNICITY","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":187.0},
        'user49':{"bio":"elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a","birth_date":"1984-11-12","user_id":100,"body_type":"CURVY","hair_colour":"BALD","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"OTHER ETHNICITY","hair_length":"SHAVED","relationship_status":"SEPARATED",'gender':'MALE',"height":187.0},
        'user50':{"bio":"orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla","birth_date":"1972-08-08","user_id":3,"body_type":"CURVY","hair_colour":"OTHER","looking_for":"FEMALE","children":False,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHOULDER LENGTH","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":156.6},
        'user51':{"bio":"velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur","birth_date":"1978-04-07","user_id":5,"body_type":"CURVY","hair_colour":"OTHER","looking_for":'MALE',"children":True,"education":"COLLEGE","ethnicity":"MIXED","hair_length":"LONG","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":171.9},
        'user52':{"bio":"nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien","birth_date":"1985-09-21","user_id":6,"body_type":"AVERAGE","hair_colour":"PURPLE","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"BLACK","hair_length":"LONG","relationship_status":"DIVORCED",'gender':"FEMALE","height":171.1},
        'user53':{"bio":"sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non","birth_date":"1984-09-01","user_id":7,"body_type":"A LITTLE EXTRA","hair_colour":"BLACK","looking_for":"FEMALE","children":False,"education":"HIGH SCHOOL","ethnicity":"BLACK","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":184.2},
        'user54':{"bio":"quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum","birth_date":"1985-11-22","user_id":8,"body_type":"A LITTLE EXTRA","hair_colour":"BLUE","looking_for":"FEMALE","children":False,"education":"COLLEGE","ethnicity":"ASIAN: BANGLADESHI","hair_length":"LONG","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":159.4},
        'user55':{"bio":"congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio","birth_date":"1982-05-03","user_id":9,"body_type":"MUSCULAR","hair_colour":"PURPLE","looking_for":"BOTH","children":True,"education":"COLLEGE","ethnicity":"ASIAN: INDIAN","hair_length":"AVERAGE","relationship_status":"DIVORCED",'gender':"FEMALE","height":160.3},
        'user56':{"bio":"donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum","birth_date":"1973-08-11","user_id":10,"body_type":"FIT","hair_colour":"OTHER","looking_for":"FEMALE","children":True,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: CHINESE","hair_length":"LONG","relationship_status":"WIDOWED",'gender':"FEMALE","height":150.8},
        'user57':{"bio":"non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit","birth_date":"1979-10-12","user_id":12,"body_type":"MUSCULAR","hair_colour":"GREY","looking_for":"FEMALE","children":True,"education":"COLLEGE","ethnicity":"OTHER ETHNICITY","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':"FEMALE","height":158.5},
        'user58':{"bio":"maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia","birth_date":"1985-06-10","user_id":15,"body_type":"MUSCULAR","hair_colour":"BROWN","looking_for":"BOTH","children":False,"education":"BACHELORS DEGREE","ethnicity":"WHITE","hair_length":"LONG","relationship_status":"SEPARATED",'gender':"FEMALE","height":150.3},
        'user59':{"bio":"sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis","birth_date":"1984-11-20","user_id":16,"body_type":"A LITTLE EXTRA","hair_colour":"BROWN","looking_for":"FEMALE","children":True,"education":"COLLEGE","ethnicity":"ASIAN: INDIAN","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':"FEMALE","height":186.8},
        'user60':{"bio":"eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis","birth_date":"1982-06-01","user_id":20,"body_type":"THIN","hair_colour":"PURPLE","looking_for":"FEMALE","children":True,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: CHINESE","hair_length":"SHORT","relationship_status":"WIDOWED",'gender':"FEMALE","height":154.4},
        'user61':{"bio":"mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu","birth_date":"1988-08-07","user_id":21,"body_type":"THIN","hair_colour":"BALD","looking_for":"BOTH","children":False,"education":"MASTERS","ethnicity":"ASIAN: CHINESE","hair_length":"SHOULDER LENGTH","relationship_status":"SEPARATED",'gender':"FEMALE","height":159.6},
        'user62':{"bio":"proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu pede","birth_date":"1987-04-10","user_id":24,"body_type":"FIT","hair_colour":"OTHER","looking_for":"FEMALE","children":True,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: INDIAN","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":163.3},
        'user63':{"bio":"sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis","birth_date":"1983-12-25","user_id":27,"body_type":"CURVY","hair_colour":"RED","looking_for":"BOTH","children":True,"education":"HIGH SCHOOL","ethnicity":"BLACK","hair_length":"SHOULDER LENGTH","relationship_status":"DIVORCED",'gender':"FEMALE","height":196.9},
        'user64':{"bio":"mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus","birth_date":"1979-02-04","user_id":28,"body_type":"THIN","hair_colour":"BLUE","looking_for":'MALE',"children":True,"education":"MASTERS","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHORT","relationship_status":"SEPARATED",'gender':"FEMALE","height":184.0},
        'user65':{"bio":"sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel","birth_date":"1984-12-03","user_id":29,"body_type":"AVERAGE","hair_colour":"BROWN","looking_for":'MALE',"children":False,"education":"MASTERS","ethnicity":"ASIAN: INDIAN","hair_length":"SHAVED","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":160.7},
        'user66':{"bio":"amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis","birth_date":"1979-08-01","user_id":32,"body_type":"AVERAGE","hair_colour":"PURPLE","looking_for":'MALE',"children":True,"education":"BACHELORS DEGREE","ethnicity":"ASIAN: PAKISTANI","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":157.7},
        'user67':{"bio":"cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum","birth_date":"1974-12-24","user_id":33,"body_type":"THIN","hair_colour":"BLACK","looking_for":"BOTH","children":False,"education":"BACHELORS DEGREE","ethnicity":"BLACK","hair_length":"SHORT","relationship_status":"DIVORCED",'gender':"FEMALE","height":152.1},
        'user68':{"bio":"ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis","birth_date":"1985-12-31","user_id":35,"body_type":"CURVY","hair_colour":"BLUE","looking_for":"BOTH","children":True,"education":"MASTERS","ethnicity":"ASIAN: BANGLADESHI","hair_length":"LONG","relationship_status":"SEPARATED",'gender':"FEMALE","height":161.5},
        'user69':{"bio":"quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at","birth_date":"1980-04-08","user_id":36,"body_type":"CURVY","hair_colour":"PURPLE","looking_for":'MALE',"children":False,"education":"HIGH SCHOOL","ethnicity":"ASIAN: INDIAN","hair_length":"SHAVED","relationship_status":"DIVORCED",'gender':"FEMALE","height":161.0},
        'user70':{"bio":"sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem","birth_date":"1978-03-01","user_id":37,"body_type":"MUSCULAR","hair_colour":"BLACK","looking_for":"FEMALE","children":False,"education":"PHD / POST DOCTORAL","ethnicity":"ASIAN: BANGLADESHI","hair_length":"SHORT","relationship_status":"NEVER MARRIED",'gender':"FEMALE","height":177.5},
        'user71':{"bio":"amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum","birth_date":"1985-01-13","user_id":41,"body_type":"A LITTLE EXTRA","hair_colour":"OTHER","looking_for":'MALE',"children":True,"education":"HIGH SCHOOL","ethnicity":"ASIAN: INDIAN","hair_length":"SHORT","relationship_status":"WIDOWED",'gender':"FEMALE","height":185.6},
        'user72':{"bio":"nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed","birth_date":"1975-06-26","user_id":42,"body_type":"THIN","hair_colour":"BLONDE","looking_for":"FEMALE","children":True,"education":"COLLEGE","ethnicity":"MIXED","hair_length":"AVERAGE","relationship_status":"DIVORCED",'gender':"FEMALE","height":164.5},
    }
    
    for k,v in profile.items():
        k = Profile.objects.get(pk=v['user_id'])
        k.bio = v['bio']
        k.birth_date = v['birth_date']
        k.body_type = v['body_type']
        k.hair_colour = v['hair_colour']
        k.looking_for = v['looking_for']
        k.children = v['children']
        k.education = v['education']
        k.ethnicity = v['ethnicity']
        k.hair_length = v['hair_length']
        k.relationship_status = v['relationship_status']
        k.gender = v['gender']
        k.height = v['height']
        
        k.save()
    
    
    return render(request, 'preregister.html')