from django.shortcuts import render
from profiles.models import Profile, ProfileImage
from django.db.models import Q, F
from django.db.models import Count
from django.contrib.auth.decorators import login_required
import datetime as DT
from django.contrib.auth.models import User


# Create your views here.
@login_required
def index(request):

    # Change limit
    # 'or' needed in gender check https://stackoverflow.com/questions/739776/how-do-i-do-an-or-filter-in-a-django-query
    # Exclude current user
    # Nearby Profiles
    if request.user.profile.looking_for == "BOTH":
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user_id=request.user.id).all()[:4]
    else:
        closest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user_id=request.user.id).all()[:4]
    
    # Profiles for quick match finder
    if request.user.profile.looking_for == "BOTH":
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).all()
    else:
        card_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).order_by('distance').filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).exclude(user__winks_receiver__sender_id=request.user.id).exclude(user_id=request.user.id).all()
    
    today = DT.date.today()
    one_week_ago = today - DT.timedelta(days=7)
    # Filter date_joined
    # Profiles for active most recently  
    if request.user.profile.looking_for == "BOTH":
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4]
    else:
        active_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).filter(user__date_joined__lte=one_week_ago).order_by('-user__last_login').exclude(user_id=request.user.id).all()[:4] 
    
    # Profiles for newest
    if request.user.profile.looking_for == "BOTH":
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4]
    else:
        newest_profiles = Profile.objects.nearby_locations(float(request.user.profile.cityLat), float(request.user.profile.cityLong)).filter(Q(looking_for=request.user.profile.gender) | Q(looking_for="BOTH")).filter(gender=request.user.profile.looking_for).order_by('-user__date_joined').exclude(user_id=request.user.id).all()[:4] 

    context = {
        'closest_profiles':closest_profiles,
        'active_profiles':active_profiles,
        'newest_profiles': newest_profiles,
        'card_profiles': card_profiles
    }
    
    return render(request, 'index.html', context)
    
def preregister(request):

    maleuser1 = ProfileImage(image='images/male1.jpg', user_id=1)
    maleuser2 = ProfileImage(image='images/male2.jpg', user_id=2)
    maleuser3 = ProfileImage(image='images/male3.jpg', user_id=3)
    maleuser4 = ProfileImage(image='images/male4.jpg', user_id=4)
    maleuser5 = ProfileImage(image='images/male5.jpg', user_id=5)
    maleuser6 = ProfileImage(image='images/male6.jpg', user_id=6)
    maleuser7 = ProfileImage(image='images/male7.jpg', user_id=7)
    maleuser8 = ProfileImage(image='images/male8.jpg', user_id=8)
    maleuser9 = ProfileImage(image='images/male9.jpg', user_id=9)
    maleuser10 = ProfileImage(image='images/male10.jpg', user_id=10)
    maleuser11 = ProfileImage(image='images/male11.jpg', user_id=11)
    maleuser12 = ProfileImage(image='images/male12.jpg', user_id=12)
    maleuser13 = ProfileImage(image='images/male13.jpg', user_id=13)
    maleuser14 = ProfileImage(image='images/male14.jpg', user_id=14)
    maleuser15 = ProfileImage(image='images/male15.jpg', user_id=15)
    maleuser16 = ProfileImage(image='images/male16.jpg', user_id=16)
    maleuser17 = ProfileImage(image='images/male17.jpg', user_id=17)
    maleuser18 = ProfileImage(image='images/male18.jpg', user_id=18)
    maleuser19 = ProfileImage(image='images/male19.jpg', user_id=19)
    maleuser20 = ProfileImage(image='images/male20.jpg', user_id=20)
    maleuser21 = ProfileImage(image='images/male21.jpg', user_id=21)
    maleuser22 = ProfileImage(image='images/male22.jpg', user_id=22)
    maleuser23 = ProfileImage(image='images/male23.jpg', user_id=23)
    maleuser24 = ProfileImage(image='images/male24.jpg', user_id=24)
    maleuser25 = ProfileImage(image='images/male25.jpg', user_id=25)
    maleuser26 = ProfileImage(image='images/male26.jpg', user_id=26)
    maleuser27 = ProfileImage(image='images/male27.jpg', user_id=27)
    maleuser28 = ProfileImage(image='images/male28.jpg', user_id=28)
    maleuser29 = ProfileImage(image='images/male29.jpg', user_id=29)
    maleuser30 = ProfileImage(image='images/male30.jpg', user_id=30)
    maleuser31 = ProfileImage(image='images/male31.jpg', user_id=31)
    maleuser32 = ProfileImage(image='images/male32.jpg', user_id=32)
    maleuser33 = ProfileImage(image='images/male33.jpg', user_id=33)
    maleuser34 = ProfileImage(image='images/male34.jpg', user_id=34)
    maleuser35 = ProfileImage(image='images/male35.jpg', user_id=35)
    maleuser36 = ProfileImage(image='images/male36.jpg', user_id=36)
    maleuser37 = ProfileImage(image='images/male37.jpg', user_id=37)
    maleuser38 = ProfileImage(image='images/male38.jpg', user_id=38)
    maleuser39 = ProfileImage(image='images/male39.jpg', user_id=39)
    maleuser40 = ProfileImage(image='images/male40.jpg', user_id=40)
    maleuser41 = ProfileImage(image='images/male41.jpg', user_id=41)
    maleuser42 = ProfileImage(image='images/male42.jpg', user_id=42)
    maleuser43 = ProfileImage(image='images/male43.jpg', user_id=43)
    maleuser44 = ProfileImage(image='images/male44.jpg', user_id=44)
    maleuser45 = ProfileImage(image='images/male45.jpg', user_id=45)
    maleuser46 = ProfileImage(image='images/male46.jpg', user_id=46)
    maleuser47 = ProfileImage(image='images/male47.jpg', user_id=47)
    maleuser48 = ProfileImage(image='images/male48.jpg', user_id=48)
    maleuser49 = ProfileImage(image='images/male49.jpg', user_id=49)
    maleuser50 = ProfileImage(image='images/male49.jpg', user_id=1)
    maleuser51 = ProfileImage(image='images/male48.jpg', user_id=2)
    maleuser52 = ProfileImage(image='images/male47.jpg', user_id=3)
    maleuser53 = ProfileImage(image='images/male46.jpg', user_id=4)
    maleuser54 = ProfileImage(image='images/male45.jpg', user_id=5)
    maleuser55 = ProfileImage(image='images/male44.jpg', user_id=6)
    maleuser56 = ProfileImage(image='images/male43.jpg', user_id=7)
    maleuser57 = ProfileImage(image='images/male42.jpg', user_id=8)
    maleuser58 = ProfileImage(image='images/male41.jpg', user_id=9)
    maleuser59 = ProfileImage(image='images/male40.jpg', user_id=10)
    maleuser60 = ProfileImage(image='images/male39.jpg', user_id=11)
    maleuser61 = ProfileImage(image='images/male38.jpg', user_id=12)
    maleuser62 = ProfileImage(image='images/male37.jpg', user_id=13)
    maleuser63 = ProfileImage(image='images/male36.jpg', user_id=14)
    maleuser64 = ProfileImage(image='images/male35.jpg', user_id=15)
    maleuser65 = ProfileImage(image='images/male34.jpg', user_id=16)
    maleuser66 = ProfileImage(image='images/male33.jpg', user_id=17)
    maleuser67 = ProfileImage(image='images/male32.jpg', user_id=18)
    maleuser68 = ProfileImage(image='images/male31.jpg', user_id=19)
    maleuser69 = ProfileImage(image='images/male30.jpg', user_id=20)
    maleuser70 = ProfileImage(image='images/male29.jpg', user_id=21)
    maleuser71 = ProfileImage(image='images/male28.jpg', user_id=22)
    maleuser72 = ProfileImage(image='images/male27.jpg', user_id=23)
    maleuser73 = ProfileImage(image='images/male26.jpg', user_id=24)
    maleuser74 = ProfileImage(image='images/male25.jpg', user_id=25)
    maleuser75 = ProfileImage(image='images/male24.jpg', user_id=26)
    maleuser76 = ProfileImage(image='images/male23.jpg', user_id=27)
    maleuser77 = ProfileImage(image='images/male22.jpg', user_id=28)
    maleuser78 = ProfileImage(image='images/male21.jpg', user_id=29)
    maleuser79 = ProfileImage(image='images/male20.jpg', user_id=30)
    maleuser80 = ProfileImage(image='images/male19.jpg', user_id=31)
    maleuser81 = ProfileImage(image='images/male18.jpg', user_id=32)
    maleuser82 = ProfileImage(image='images/male17.jpg', user_id=33)
    maleuser83 = ProfileImage(image='images/male16.jpg', user_id=34)
    maleuser84 = ProfileImage(image='images/male15.jpg', user_id=35)
    maleuser85 = ProfileImage(image='images/male14.jpg', user_id=36)
    maleuser86 = ProfileImage(image='images/male13.jpg', user_id=37)
    maleuser87 = ProfileImage(image='images/male12.jpg', user_id=38)
    maleuser88 = ProfileImage(image='images/male11.jpg', user_id=39)
    maleuser89 = ProfileImage(image='images/male10.jpg', user_id=40)
    maleuser90 = ProfileImage(image='images/male9.jpg', user_id=41)
    maleuser91 = ProfileImage(image='images/male8.jpg', user_id=42)
    maleuser92 = ProfileImage(image='images/male7.jpg', user_id=43)
    maleuser93 = ProfileImage(image='images/male6.jpg', user_id=44)
    maleuser94 = ProfileImage(image='images/male5.jpg', user_id=45)
    maleuser95 = ProfileImage(image='images/male4.jpg', user_id=46)
    maleuser96 = ProfileImage(image='images/male3.jpg', user_id=47)
    maleuser97 = ProfileImage(image='images/male2.jpg', user_id=48)
    maleuser98 = ProfileImage(image='images/male1.jpg', user_id=49)
    
    femaleuser1 = ProfileImage(image='images/female1.jpg', user_id=50)
    femaleuser2 = ProfileImage(image='images/female2.jpg', user_id=51)
    femaleuser3 = ProfileImage(image='images/female3.jpg', user_id=52)
    femaleuser4 = ProfileImage(image='images/female4.jpg', user_id=53)
    femaleuser5 = ProfileImage(image='images/female5.jpg', user_id=54)
    femaleuser6 = ProfileImage(image='images/female6.jpg', user_id=55)
    femaleuser7 = ProfileImage(image='images/female7.jpg', user_id=56)
    femaleuser8 = ProfileImage(image='images/female8.jpg', user_id=57)
    femaleuser9 = ProfileImage(image='images/female9.jpg', user_id=58)
    femaleuser10 = ProfileImage(image='images/female10.jpg', user_id=59)
    femaleuser11 = ProfileImage(image='images/female11.jpg', user_id=60)
    femaleuser12 = ProfileImage(image='images/female12.jpg', user_id=61)
    femaleuser13 = ProfileImage(image='images/female13.jpg', user_id=62)
    femaleuser14 = ProfileImage(image='images/female14.jpg', user_id=63)
    femaleuser15 = ProfileImage(image='images/female15.jpg', user_id=64)
    femaleuser16 = ProfileImage(image='images/female16.jpg', user_id=65)
    femaleuser17 = ProfileImage(image='images/female17.jpg', user_id=66)
    femaleuser18 = ProfileImage(image='images/female18.jpg', user_id=67)
    femaleuser19 = ProfileImage(image='images/female19.jpg', user_id=68)
    femaleuser20 = ProfileImage(image='images/female20.jpg', user_id=69)
    femaleuser21 = ProfileImage(image='images/female21.jpg', user_id=70)
    femaleuser22 = ProfileImage(image='images/female22.jpg', user_id=71)
    femaleuser23 = ProfileImage(image='images/female23.jpg', user_id=72)
    femaleuser24 = ProfileImage(image='images/female24.jpg', user_id=73)
    femaleuser25 = ProfileImage(image='images/female25.jpg', user_id=74)
    femaleuser26 = ProfileImage(image='images/female26.jpg', user_id=75)
    femaleuser27 = ProfileImage(image='images/female27.jpg', user_id=76)
    femaleuser28 = ProfileImage(image='images/female28.jpg', user_id=77)
    femaleuser29 = ProfileImage(image='images/female29.jpg', user_id=78)
    femaleuser30 = ProfileImage(image='images/female30.jpg', user_id=79)
    femaleuser31 = ProfileImage(image='images/female31.jpg', user_id=80)
    femaleuser32 = ProfileImage(image='images/female32.jpg', user_id=81)
    femaleuser33 = ProfileImage(image='images/female33.jpg', user_id=82)
    femaleuser34 = ProfileImage(image='images/female34.jpg', user_id=83)
    femaleuser35 = ProfileImage(image='images/female35.jpg', user_id=84)
    femaleuser36 = ProfileImage(image='images/female36.jpg', user_id=85)
    femaleuser37 = ProfileImage(image='images/female37.jpg', user_id=86)
    femaleuser38 = ProfileImage(image='images/female38.jpg', user_id=87)
    femaleuser39 = ProfileImage(image='images/female39.jpg', user_id=88)
    femaleuser40 = ProfileImage(image='images/female40.jpg', user_id=89)
    femaleuser41 = ProfileImage(image='images/female41.jpg', user_id=90)
    femaleuser42 = ProfileImage(image='images/female42.jpg', user_id=91)
    femaleuser43 = ProfileImage(image='images/female43.jpg', user_id=92)
    femaleuser44 = ProfileImage(image='images/female44.jpg', user_id=93)
    femaleuser45 = ProfileImage(image='images/female45.jpg', user_id=94)
    femaleuser46 = ProfileImage(image='images/female46.jpg', user_id=95)
    femaleuser47 = ProfileImage(image='images/female47.jpg', user_id=96)
    femaleuser48 = ProfileImage(image='images/female48.jpg', user_id=97)
    femaleuser49 = ProfileImage(image='images/female49.jpg', user_id=98)
    femaleuser50 = ProfileImage(image='images/female50.jpg', user_id=99)
    femaleuser51 = ProfileImage(image='images/female51.jpg', user_id=100)
    femaleuser52 = ProfileImage(image='images/female52.jpg', user_id=101)
    femaleuser53 = ProfileImage(image='images/female53.jpg', user_id=102)
    femaleuser54 = ProfileImage(image='images/female53.jpg', user_id=50)
    femaleuser55 = ProfileImage(image='images/female52.jpg', user_id=51)
    femaleuser56 = ProfileImage(image='images/female51.jpg', user_id=52)
    femaleuser57 = ProfileImage(image='images/female50.jpg', user_id=53)
    femaleuser58 = ProfileImage(image='images/female49.jpg', user_id=54)
    femaleuser59 = ProfileImage(image='images/female48.jpg', user_id=55)
    femaleuser60 = ProfileImage(image='images/female47.jpg', user_id=56)
    femaleuser61 = ProfileImage(image='images/female46.jpg', user_id=57)
    femaleuser62 = ProfileImage(image='images/female45.jpg', user_id=58)
    femaleuser63 = ProfileImage(image='images/female44.jpg', user_id=59)
    femaleuser64 = ProfileImage(image='images/female43.jpg', user_id=60)
    femaleuser65 = ProfileImage(image='images/female42.jpg', user_id=61)
    femaleuser66 = ProfileImage(image='images/female41.jpg', user_id=62)
    femaleuser67 = ProfileImage(image='images/female40.jpg', user_id=63)
    femaleuser68 = ProfileImage(image='images/female39.jpg', user_id=64)
    femaleuser69 = ProfileImage(image='images/female38.jpg', user_id=65)
    femaleuser70 = ProfileImage(image='images/female37.jpg', user_id=66)
    femaleuser71 = ProfileImage(image='images/female36.jpg', user_id=67)
    femaleuser72 = ProfileImage(image='images/female35.jpg', user_id=68)
    femaleuser73 = ProfileImage(image='images/female34.jpg', user_id=69)
    femaleuser74 = ProfileImage(image='images/female33.jpg', user_id=70)
    femaleuser75 = ProfileImage(image='images/female32.jpg', user_id=71)
    femaleuser76 = ProfileImage(image='images/female31.jpg', user_id=72)
    femaleuser77 = ProfileImage(image='images/female30.jpg', user_id=73)
    femaleuser78 = ProfileImage(image='images/female29.jpg', user_id=74)
    femaleuser79 = ProfileImage(image='images/female28.jpg', user_id=75)
    femaleuser80 = ProfileImage(image='images/female27.jpg', user_id=76)
    femaleuser81 = ProfileImage(image='images/female26.jpg', user_id=77)
    femaleuser82 = ProfileImage(image='images/female25.jpg', user_id=78)
    femaleuser83 = ProfileImage(image='images/female24.jpg', user_id=79)
    femaleuser84 = ProfileImage(image='images/female23.jpg', user_id=80)
    femaleuser85 = ProfileImage(image='images/female22.jpg', user_id=81)
    femaleuser86 = ProfileImage(image='images/female21.jpg', user_id=82)
    femaleuser87 = ProfileImage(image='images/female20.jpg', user_id=83)
    femaleuser88 = ProfileImage(image='images/female19.jpg', user_id=84)
    femaleuser89 = ProfileImage(image='images/female18.jpg', user_id=85)
    femaleuser90 = ProfileImage(image='images/female17.jpg', user_id=86)
    femaleuser91 = ProfileImage(image='images/female16.jpg', user_id=87)
    femaleuser92 = ProfileImage(image='images/female15.jpg', user_id=88)
    femaleuser93 = ProfileImage(image='images/female14.jpg', user_id=89)
    femaleuser94 = ProfileImage(image='images/female13.jpg', user_id=90)
    femaleuser95 = ProfileImage(image='images/female12.jpg', user_id=91)
    femaleuser96 = ProfileImage(image='images/female11.jpg', user_id=92)
    femaleuser97 = ProfileImage(image='images/female10.jpg', user_id=93)
    femaleuser98 = ProfileImage(image='images/female9.jpg', user_id=94)
    femaleuser99 = ProfileImage(image='images/female8.jpg', user_id=95)
    femaleuser100 = ProfileImage(image='images/female7.jpg', user_id=96)
    femaleuser101 = ProfileImage(image='images/female6.jpg', user_id=97)
    femaleuser102 = ProfileImage(image='images/female5.jpg', user_id=98)
    femaleuser103 = ProfileImage(image='images/female4.jpg', user_id=99)
    femaleuser104 = ProfileImage(image='images/female3.jpg', user_id=100)
    femaleuser105 = ProfileImage(image='images/female2.jpg', user_id=101)
    femaleuser106 = ProfileImage(image='images/female1.jpg', user_id=102)


    maleuser1.save()
    maleuser2.save()
    maleuser3.save()
    maleuser4.save()
    maleuser5.save()
    maleuser6.save()
    maleuser7.save()
    maleuser8.save()
    maleuser9.save()
    maleuser10.save()
    maleuser11.save()
    maleuser12.save()
    maleuser13.save()
    maleuser14.save()
    maleuser15.save()
    maleuser16.save()
    maleuser17.save()
    maleuser18.save()
    maleuser19.save()
    maleuser20.save()
    maleuser21.save()
    maleuser22.save()
    maleuser23.save()
    maleuser24.save()
    maleuser25.save()
    maleuser26.save()
    maleuser27.save()
    maleuser28.save()
    maleuser29.save()
    maleuser30.save()
    maleuser31.save()
    maleuser32.save()
    maleuser33.save()
    maleuser34.save()
    maleuser35.save()
    maleuser36.save()
    maleuser37.save()
    maleuser38.save()
    maleuser39.save()
    maleuser40.save()
    maleuser41.save()
    maleuser42.save()
    maleuser43.save()
    maleuser44.save()
    maleuser45.save()
    maleuser46.save()
    maleuser47.save()
    maleuser48.save()
    maleuser49.save()
    maleuser50.save()
    maleuser51.save()
    maleuser52.save()
    maleuser53.save()
    maleuser54.save()
    maleuser55.save()
    maleuser56.save()
    maleuser57.save()
    maleuser58.save()
    maleuser59.save()
    maleuser60.save()
    maleuser61.save()
    maleuser62.save()
    maleuser63.save()
    maleuser64.save()
    maleuser65.save()
    maleuser66.save()
    maleuser67.save()
    maleuser68.save()
    maleuser69.save()
    maleuser70.save()
    maleuser71.save()
    maleuser72.save()
    maleuser73.save()
    maleuser74.save()
    maleuser75.save()
    maleuser76.save()
    maleuser77.save()
    maleuser78.save()
    maleuser79.save()
    maleuser80.save()
    maleuser81.save()
    maleuser82.save()
    maleuser83.save()
    maleuser84.save()
    maleuser85.save()
    maleuser86.save()
    maleuser87.save()
    maleuser88.save()
    maleuser89.save()
    maleuser90.save()
    maleuser91.save()
    maleuser92.save()
    maleuser93.save()
    maleuser94.save()
    maleuser95.save()
    maleuser96.save()
    maleuser97.save()
    maleuser98.save()
    
    femaleuser1.save()
    femaleuser2.save()
    femaleuser3.save()
    femaleuser4.save()
    femaleuser5.save()
    femaleuser6.save()
    femaleuser7.save()
    femaleuser8.save()
    femaleuser9.save()
    femaleuser10.save()
    femaleuser11.save()
    femaleuser12.save()
    femaleuser13.save()
    femaleuser14.save()
    femaleuser15.save()
    femaleuser16.save()
    femaleuser17.save()
    femaleuser18.save()
    femaleuser19.save()
    femaleuser20.save()
    femaleuser21.save()
    femaleuser22.save()
    femaleuser23.save()
    femaleuser24.save()
    femaleuser25.save()
    femaleuser26.save()
    femaleuser27.save()
    femaleuser28.save()
    femaleuser29.save()
    femaleuser30.save()
    femaleuser31.save()
    femaleuser32.save()
    femaleuser33.save()
    femaleuser34.save()
    femaleuser35.save()
    femaleuser36.save()
    femaleuser37.save()
    femaleuser38.save()
    femaleuser39.save()
    femaleuser40.save()
    femaleuser41.save()
    femaleuser42.save()
    femaleuser43.save()
    femaleuser44.save()
    femaleuser45.save()
    femaleuser46.save()
    femaleuser47.save()
    femaleuser48.save()
    femaleuser49.save()
    femaleuser50.save()
    femaleuser51.save()
    femaleuser52.save()
    femaleuser53.save()
    femaleuser54.save()
    femaleuser55.save()
    femaleuser56.save()
    femaleuser57.save()
    femaleuser58.save()
    femaleuser59.save()
    femaleuser60.save()
    femaleuser61.save()
    femaleuser62.save()
    femaleuser63.save()
    femaleuser64.save()
    femaleuser65.save()
    femaleuser66.save()
    femaleuser67.save()
    femaleuser68.save()
    femaleuser69.save()
    femaleuser70.save()
    femaleuser71.save()
    femaleuser72.save()
    femaleuser73.save()
    femaleuser74.save()
    femaleuser75.save()
    femaleuser76.save()
    femaleuser77.save()
    femaleuser78.save()
    femaleuser79.save()
    femaleuser80.save()
    femaleuser81.save()
    femaleuser82.save()
    femaleuser83.save()
    femaleuser84.save()
    femaleuser85.save()
    femaleuser86.save()
    femaleuser87.save()
    femaleuser88.save()
    femaleuser89.save()
    femaleuser90.save()
    femaleuser91.save()
    femaleuser92.save()
    femaleuser93.save()
    femaleuser94.save()
    femaleuser95.save()
    femaleuser96.save()
    femaleuser97.save()
    femaleuser98.save()
    femaleuser99.save()
    femaleuser100.save()
    femaleuser101.save()
    femaleuser102.save()
    femaleuser103.save()
    femaleuser104.save()
    femaleuser105.save()
    femaleuser106.save()
    
    
    return render(request, 'preregister.html')