# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-04 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190504_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='conversation',
        ),
    ]
